name: nuxt_prod
services:
  nuxt:
    build:
      context: .
      dockerfile_inline: |
        FROM node:22-alpine

        WORKDIR /opt/frontend

        COPY . .
        
        RUN corepack enable pnpm \
        && corepack prepare pnpm@10.0 --activate \
        && pnpm config set strict-ssl false --global \
        && pnpm install
        
        EXPOSE 3000
        CMD ["/bin/sh", "-c", "pnpm generate;npx serve .output/public -l 4000"]
    restart: always
    ports:
      # owner:container
      - "3000:4000"
    extra_hosts:
      - "localhost:host-gateway"
    tmpfs:
      - /tmp
