services:
  nuxt:
    build:
      context: .
      dockerfile_inline: |
        FROM node:21

        WORKDIR /opt/frontend

        COPY . .
        
        RUN corepack enable pnpm \
        && corepack prepare pnpm@latest --activate \
        && pnpm config set strict-ssl false --global \
        && pnpm install \
        && pnpm run build

        EXPOSE 3000
        CMD ["pnpm", "run", "preview"]
    restart: always
    ports:
      # owner:container
      - "3000:3000"
    extra_hosts:
      - "localhost:host-gateway"
