services:
  nuxt:
    build:
      context: .
      dockerfile_inline: |
        FROM node:21

        WORKDIR /opt/frontend

        COPY package.json .
        COPY tsconfig.json .
        COPY pnpm-lock.yaml .
        
        RUN corepack enable pnpm \
        && corepack prepare pnpm@latest --activate \
        && pnpm config set strict-ssl false --global \
        && pnpm install

        EXPOSE 3000
        CMD ["pnpm", "run", "dev"]
    restart: always
    ports:
      # owner:container
      - "3000:3000"
    volumes:
      - ${FRONTEND_PATH:-./public}:/opt/frontend/docs
      - ${FRONTEND_PATH:-./public}:/opt/frontend/eslint
      - ${FRONTEND_PATH:-./public}:/opt/frontend/public
      - ${FRONTEND_PATH:-./src}:/opt/frontend/src
      - ${FRONTEND_PATH:-./.eslintignore}:/opt/frontend/.eslintignore
      - ${FRONTEND_PATH:-./.eslintrc.js}:/opt/frontend/.eslintrc.js
      - ${FRONTEND_PATH:-./.env}:/opt/frontend/.env
      - ${FRONTEND_PATH:-./.npmrc}:/opt/frontend/.npmrc
      - ${FRONTEND_PATH:-./.prettierrc.json}:/opt/frontend/.prettierrc.json
      - ${FRONTEND_PATH:-./app.vue}:/opt/frontend/app.vue
      - ${FRONTEND_PATH:-./nuxt.config.ts}:/opt/frontend/nuxt.config.ts
    extra_hosts:
      - "localhost:host-gateway"
